services:
  db:
    image: mysql:8.0-debian
    container_name: biblioteca
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gr4_db
      MYSQL_USER: user_gr4
      MYSQL_PASSWORD: user_gr4
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  flask-app:
    build: .
    container_name: flask_agenda
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=10.3.29.20"
      - DB_PORT=33060
      - DB_USER=user_gr4
      - DB_PASSWORD=user_gr4
      - DB_NAME=gr4_db
    env_file:
      - .env

volumes:
  mysql_data: